# docker-compose.yml
# ----------------------------------------------------------------------------
# Composes Docker containers and volumes to a runnable Quarkus application
# ----------------------------------------------------------------------------
#
---
services:

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
      POSTGRES_PORT: "5432"
      POSTGRES_DB: cloudtrain
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "--username", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  downstream:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-monitoring-downstream:latest
    environment:
      DOCKER_JAVA_OPTS: -Xms1g -Xmx1g
      SPRING_PROFILES_ACTIVE: "cloud"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain

  backend:
    image: docker.cloudtrain.aws.msgoat.eu/cloudtrain/cnj-monitoring-backend-quarkus:latest
    ports:
      - "38090:8080"
    environment:
      DOCKER_JAVA_OPTS: "-Xms1g -Xmx1g"
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: "https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain/protocol/openid-connect/certs"
      MP_JWT_VERIFY_ISSUER: "https://oidc.cloudtrain.aws.msgoat.eu/realms/cloudtrain"
      CLOUDTRAIN_SERVICES_GRANTEDPERMISSIONS_MP_REST_URL: "http://downstream:8080"
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: changeit
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/cloudtrain
    depends_on:
      postgres:
        condition: service_healthy
      downstream:
        condition: service_started

volumes:

  postgres-data:
